trigger:
- main

variables:
  acrLoginServer: 'loveluacr.azurecr.io'
  backendImage: 'backend-api'
  frontendImage: 'frontend'
  tag: '$(Build.BuildId)'
  namespace: 'three-tier'
  aksResourceGroup: 'dev'
  aksCluster: 'aks-3tier'

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: BuildPush
    pool:
      #vmImage: ubuntu-latest
      name: Default

    steps:
    - task: Docker@2
      displayName: Build backend image
      inputs:
        command: build
        repository: $(backendImage)
        dockerfile: backend/backend/backend/Dockerfile
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build frontend image
      inputs:
        command: build
        repository: $(frontendImage)
        dockerfile: frontend/Dockerfile
        tags: |
          $(tag)
    # Install Trivy
    - script: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
      displayName: Install Trivy
    #  Scan Backend
    - script: |
        trivy image \
        --exit-code 1 \
        --severity HIGH,CRITICAL \
        $(acrLoginServer)/$(backendImage):$(tag)
      displayName: Scan Backend Image

    #  Scan Frontend
    - script: |
        trivy image \
          --exit-code 1 \
          --severity HIGH,CRITICAL \
          $(acrLoginServer)/$(frontendImage):$(tag)
      displayName: Scan Frontend Image
    
    - task: Docker@2
      displayName: Push backend image
      inputs:
        command: push
        repository: $(backendImage)
        containerRegistry: acr-connection
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push frontend image
      inputs:
        command: push
        repository: $(frontendImage)
        containerRegistry: acr-connection
        tags: |
          $(tag)


- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: DeployAKS
    pool:
      #vmImage: ubuntu-latest
      name: Default

    steps:
    - checkout: self

    - task: KubernetesManifest@1
      displayName: Deploy manifests to AKS
      inputs:
        action: deploy
        connectionType: azureResourceManager
        azureSubscriptionConnection: azure-rm-connection
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksCluster)
        namespace: $(namespace)
        manifests: |
          k8s/01-namespace.yaml
          k8s/02-backend-serviceaccount.yaml
          k8s/03-secretproviderclass.yaml
          k8s/04-backend-deployment.yaml
          k8s/05-backend-service.yaml
          k8s/06-frontend-deployment.yaml
          k8s/07-frontend-service.yaml
          k8s/08-ingress.yaml
        containers: |
          $(acrLoginServer)/$(backendImage):$(tag)
          $(acrLoginServer)/$(frontendImage):$(tag)
