trigger:
- main

variables:
  acrLoginServer: 'loveluacr.azurecr.io'
  backendImage: 'backend-api'
  frontendImage: 'frontend'
  tag: '$(Build.BuildId)'
  namespace: 'three-tier'
  aksResourceGroup: 'dev'
  aksCluster: 'aks-3tier'

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: BuildPush
    pool:
      #vmImage: ubuntu-latest
      name: Default

    steps:
    - task: SonarQubePrepare@7
      displayName: Prepare SonarQube analysis
      inputs:
        SonarQube: 'sonarqube-connection'
        scannerMode: 'dotnet'
        projectKey: 'three-tier-backend'
        projectName: 'three-tier-backend'

    - script: |
        dotnet restore backend/backend/backend/backend.csproj
        dotnet build backend/backend/backend/backend.csproj --configuration Release --no-restore
      displayName: Build backend for SonarQube

    - task: SonarQubeAnalyze@7
      displayName: Run SonarQube analysis

    - task: SonarQubePublish@7
      displayName: Publish SonarQube Quality Gate
      inputs:
        pollingTimeoutSec: '300'

    - task: Docker@2
      displayName: Build backend image
      inputs:
        command: build
        repository: $(backendImage)
        dockerfile: backend/backend/backend/Dockerfile
        containerRegistry: acr-connection
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build frontend image
      inputs:
        command: build
        repository: $(frontendImage)
        dockerfile: frontend/Dockerfile
        containerRegistry: acr-connection
        tags: |
          $(tag)
    # Install Trivy
    - script: |
         if ! command -v trivy &> /dev/null
         then
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install -y trivy
            else
            echo "Trivy already installed"
          fi
      displayName: Install Trivy
    #  Scan Backend
    - script: |
        trivy image --ignorefile .trivyignore \
          --severity CRITICAL \
          -f table \
          -o backend-report.txt \
          $(acrLoginServer)/$(backendImage):$(tag)

        trivy image --ignorefile .trivyignore \
        --exit-code 1 \
        --severity CRITICAL \
        $(acrLoginServer)/$(backendImage):$(tag)
      displayName: Scan Backend Image
    - publish: backend-report.txt
      artifact: trivy-backend
      condition: always()
      
    #  Scan Frontend
    - script: |
        trivy image --ignorefile .trivyignore \
          --severity CRITICAL \
          -f table \
          -o frontend-report.txt \
          $(acrLoginServer)/$(frontendImage):$(tag)

        trivy image --ignorefile .trivyignore \
          --exit-code 1 \
          --severity CRITICAL \
          $(acrLoginServer)/$(frontendImage):$(tag)
      displayName: Scan Frontend Image
    - publish: frontend-report.txt
      artifact: trivy-frontend
      condition: always()

    - task: Docker@2
      displayName: Push backend image
      inputs:
        command: push
        dockerfile: backend/backend/backend/Dockerfile
        repository: $(backendImage)
        containerRegistry: acr-connection
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push frontend image
      inputs:
        command: push
        dockerfile: frontend/Dockerfile
        repository: $(frontendImage)
        containerRegistry: acr-connection
        tags: |
          $(tag)


- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: DeployAKS
    pool:
      #vmImage: ubuntu-latest
      name: Default

    steps:
    - checkout: self

    - task: KubernetesManifest@1
      displayName: Deploy manifests to AKS
      inputs:
        action: deploy
        connectionType: azureResourceManager
        azureSubscriptionConnection: azure-rm-connection
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksCluster)
        namespace: $(namespace)
        manifests: |
          k8s/01-namespace.yaml
          k8s/02-backend-serviceaccount.yaml
          k8s/03-secretproviderclass.yaml
          k8s/04-backend-deployment.yaml
          k8s/05-backend-service.yaml
          k8s/06-frontend-deployment.yaml
          k8s/07-frontend-service.yaml
          k8s/08-ingress.yaml
        containers: |
          $(acrLoginServer)/$(backendImage):$(tag)
          $(acrLoginServer)/$(frontendImage):$(tag)
