apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-keyvault-secrets
  namespace: three-tier
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "0f48880b-ce16-4970-9f2a-dfd312bc2c41"
    keyvaultName: "kv-3tier-app-lovelu2"
    tenantId: "2a1f0b68-fdde-4151-9edf-97628de42914"
    objects: |
      array:
        - |
          objectName: SqlConnectionString
          objectType: secret
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: SqlConnectionString
          key: SqlConnectionString